#Mystvale Academy leaderboard
#Fri May 22 04:34:08 PST 2026
entry.0.completedAt=2026-05-21T20\:34\:08.289098600Z
entry.0.edgeMillis=79938
entry.0.forestMillis=271762
entry.0.forsakenMillis=243498
entry.0.heroClass=Mage
entry.0.heroName=Mleux, the Windwhisperer
entry.0.overallMillis=271762
entry.count=1
